config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions" }
  # sessions request should be handle by sessins controller
  root to: 'pages#home'

  get "analytics", to: "pages#analytics"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected
  def after_sign_in_path_for(resource)
  	# here i make the request to the waybook api

    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/controllers/concerns/charts_nationality.rb
module ChartsNationality
  extend ActiveSupport::Concern

  included do
    helper_method :way_group
  end

  def self.filter_by_division(items, division_name)
    items = items.select { |profile_hash| profile_hash["division"]["name"] == division_name }
  end

  def self.item_counts(items)
    nationalities = items.map { |profile_hash| profile_hash["nationality"] }
    items_counts = CountObjectsInArrayService.execute(nationalities)
  end

  def self.way_group_data_x(items_counts)
    items_counts.keys.to_json.html_safe
  end

  def self.way_group_data_y(items_counts)
    items_counts.map { |key, value| value }
  end
  
end

app/controllers/pages_controller.rb
require 'open-uri'

class PagesController < ApplicationController
  include ChartsNationality
  skip_before_action :authenticate_user!, only: [:home]
  
  

  def analytics
    user_token = session["authentication_token"]
    current_user_email = current_user.email

  	url = "https://way-book.herokuapp.com/api/v1/profiles?user_email=#{current_user_email}&user_token=#{user_token}"

  	html_file = open(url).read
  	json_response = JSON.parse(html_file)

    full_names = json_response.map { |profile_hash| "#{profile_hash["first_name"]} #{profile_hash["last_name"]}" }

    # graph 1
    # employees per division
  	employee_divisions = json_response.map { |profile_hash| profile_hash["division"] }
    counted_objects = CountObjectsInArrayService.execute(employee_divisions)
    keys = counted_objects.keys
    totals = counted_objects.map { |key, value| value }

    @division_names = keys.to_json.html_safe
    @division_names = ["WAY HR", "WAY People+", "WAY Engineering", "WAY IT"].to_json.html_safe
    @num_employees_per_division = totals

    # employees per nationality way group
    items_counts = ChartsNationality.item_counts(json_response)
    @nationalities_names = ChartsNationality.way_group_data_x(items_counts)
    @num_employees_per_nationality = ChartsNationality.way_group_data_y(items_counts).sort.reverse

    # employees per nationality engineering division
    items_engineering = ChartsNationality.filter_by_division(json_response, "WAY Engineering GmbH")
    items_counts = ChartsNationality.item_counts(items_engineering)
    @nationalities_names_engineering = ChartsNationality.way_group_data_x(items_counts)
    @num_employees_per_nationality_engineering = ChartsNationality.way_group_data_y(items_counts).sort.reverse

    # employees per nationality people division
    items_people = ChartsNationality.filter_by_division(json_response, "WAY People+ GmbH")
    items_counts = ChartsNationality.item_counts(items_people)
    @nationalities_names_people = ChartsNationality.way_group_data_x(items_counts)
    @num_employees_per_nationality_people = ChartsNationality.way_group_data_y(items_counts).sort.reverse

    # # company average age
    active_employees = json_response.select { |hash| hash["endway"].nil? }
    birthdays = active_employees.map { |profile_hash| Date.parse(profile_hash["birthday"]) }

    first_years_days = []
    years = (2006...Date.today.year).to_a

    years.each do |year|
      first_years_days << Date.new(year, 1, 1)
    end

    @monthly_ages_averages = []
    first_years_days.each do |first_year_day|
      ages = birthdays.map { |birthday| (first_year_day - birthday).to_f / 365.0 }
      ages_average = ages.inject(0.0) { |sum, el| sum + el } / ages.size
      @monthly_ages_averages << ages_average
    end

    @first_years_days = first_years_days.map { |first_year_day| first_year_day.strftime("%b %y") }.to_json.html_safe

    ### age of the way group
    ages = birthdays.map { |birthday| (Date.today - birthday).to_f / 365.0 }

    ages_18_30 = []
    ages_31_40 = []
    ages_41_50 = []
    ages_51_65 = []

    ages.each do |age|
      if age <= 30.0
        ages_18_30 << age
      elsif age <= 40.0 and age > 30
        ages_31_40 << age
      elsif age <= 50.0 and age > 40
        ages_41_50 << age
      elsif age <= 65.0 and age > 50
        ages_51_65 << age
      else

      end
    end
    @num_employee_per_age_group_array = [ages_18_30.count, ages_31_40.count, ages_41_50.count, ages_51_65.count]

    # num employees per country
    countries = json_response.map { |profile_hash| profile_hash["nationality"] }

    countries_counts = Hash.new 0
    countries.each do |division|
      countries_counts[division] += 1
    end

    # new employees per month
    months = (1..12).to_a
    years = (2006..Date.today.year).to_a

    years_hash =  Hash.new
    years.each do |year|
      months_hash = Hash.new
      years_hash[year] = months_hash
      months.each do |month|
        years_hash[year][month] = 0
      end
    end

    startways = json_response.map { |profile_hash| Date.parse(profile_hash["startway"]) }
    startways.each do |startway|
      year = startway.year
      month = startway.month
      years_hash[year][month] += years_hash[year][month] + 1
    end

    # convert to long array
    @incorporations = []
    arrays = years_hash.map { |key, value| value.map { |key, value| value } }
    arrays.each do |my_array|
      my_array.each do |number|
        @incorporations << number
      end
    end

    @inc_months = []
    years_hash.each do |key, value|
      year = key
      value.each do |key, test|
        @inc_months << Date.new(year, key, 1).strftime("%b %y")
      end
    end
    @inc_months = @inc_months.to_json.html_safe

    puts html_file
  end

  def home
  	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

	def create
		super
		user_info = sign_user_into_api
		session['authentication_token'] = user_info["authentication_token"]
	end

	private

	def sign_user_into_api
		# after devise sign in, we have a params with [:user][:email], [:user][:password]
		email = user_params[:email]
		password = encrypt_password(user_params[:password])

		api_url = 'https://way-book.herokuapp.com/users/sign_in.json'
		# .json this is to force devise to send us a json response, instead of the normal redirect 
		response = HTTParty.post(
			api_url, body: {
				user: {email: email, password: password}
			}
		)
		JSON.parse(response.body)
	end

	def encrypt_password(str)
	  cipher_salt1 = 'some-random-salt-'
	  cipher_salt2 = 'another-random-salt-'
	  cipher = OpenSSL::Cipher.new('AES-128-ECB').encrypt
	  cipher.key = OpenSSL::PKCS5.pbkdf2_hmac_sha1(cipher_salt1, cipher_salt2, 20_000, cipher.key_len)
	  encrypted = cipher.update(str) + cipher.final
	  encrypted.unpack('H*')[0].upcase
	end

	def user_params
		params.require(:user).permit(:email, :password)
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WAY Book Analytics</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <!-- bootstrap & jquery -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

    <!-- jquery -->
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.8.19/jquery-ui.min.js" %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Satisfy|Gloria+Hallelujah" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- Chart.js cdn -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:chart_js) %>
  </body>
</html>

app/views/pages/analytics.html.erb
<div class="analytics-page">

	<%= render "pages/analytics/left_menu" %>

	<div class="charts-wrapper">

		<div class="title-header">
			Number employees
		</div>

		<div class="charts-row">
			<!-- CHART 1:  -->
			<div class="">
				<%= render "pages/analytics/chart_num_employees_per_division" %>
			</div>
			<!-- CHART 2:  -->
			<div class="">
				<%= render "pages/analytics/chart_num_employees_per_nationality" %>
			</div>
		</div>

		<div class="title-header">
			Number employees per division
		</div>

		<div class="charts-row">
			<!-- CHART 3:  -->
			<div class="">
				<%= render "pages/analytics/chart_num_employees_per_nationality_engineering" %>
			</div>
			<!-- CHART 4:  -->
			<div class="">
				<%= render "pages/analytics/chart_num_employees_per_nationality_people" %>
			</div>
		</div>

		<div class="title-header">
			Age analysis
		</div>

		<div class="charts-row">
			<!-- CHART 3:  -->
			<div class="">
				<%= render "pages/analytics/chart_evolution_average_age" %>
			</div>
			<!-- CHART 4:  -->
			<div class="">
				<%= render "pages/analytics/chart_num_employees_per_age_group" %>
			</div>
		</div>

		<div class="title-header">
			New employees evolution
		</div>

		<div class="charts-row">
			<%= render "pages/analytics/chart_new_employees_per_month" %>
		</div>

	</div>

</div>

app/views/pages/analytics/_chart_evolution_average_age.html.erb
<div class="chart-wrapper">
	<div class="title">
		Evolution average age
	</div>
	<div class="canvas-wrapper-one-third">
		<canvas id="evolution_average_age" height="100" width="100"></canvas>
	</div>
</div>

<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	let firstYearsDays = <%= @first_years_days %>;
		let monthlyAgesAverages = <%= @monthly_ages_averages %>;
		linearChartGenerator(firstYearsDays, monthlyAgesAverages);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_chart_new_employees_per_month.html.erb
<!-- CHART 1: Num. employees per division -->
<div class="chart-wrapper">
	<div class="title">
		New Employees per month
	</div>
	<div class="canvas-wrapper-three-thirds">
		<canvas id="new_employees_per_month" height="100" width="300"></canvas>
	</div>
</div>

<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	attr = {
	  		dataX: <%= @inc_months %>,
	  		dataY: <%= @incorporations %>,
	  		id: "new_employees_per_month",
	  		type: "bar",
	  		xAxesTicksAutoSkip: true
	  	};
		chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_chart_num_employees_per_age_group.html.erb
<div class="chart-wrapper">
	<div class="title">
		Num. employees per age group
	</div>
	<div class="canvas-wrapper-one-third">
		<canvas id="num_employee_per_age_group_array" height="100" width="100"></canvas>
	</div>
</div>


<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	attr = {
	  		dataX: ["< 30", "31 - 40", "41 - 50", "51 - 65"],
	  		dataY: <%= @num_employee_per_age_group_array %>,
	  		id: "num_employee_per_age_group_array",
	  		type: "bar",
	  		xAxesTicksAutoSkip: true
	  	}
		chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_chart_num_employees_per_division.html.erb
<!-- CHART 1: Num. employees per division -->
<div class="chart-wrapper">
	<div class="title">
		Num. employees per division
	</div>
	<div class="canvas-wrapper-one-third">
		<canvas id="num_employees_per_division" height="100" width="100"></canvas>
	</div>
</div>

<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	// Chart 1: num employees per division
  	  	let attr = {
  	  		dataX: <%= @division_names %>,
  	  		dataY: <%= @num_employees_per_division %>,
  	  		id: "num_employees_per_division",
  	  		type: "bar",
	  		xAxesTicksAutoSkip: true
  	  	}
  		chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_chart_num_employees_per_nationality.html.erb
<div class="chart-wrapper">
	<div class="title">
		Num. employees per nationality
	</div>
	<div class="canvas-wrapper-one-third">
		<canvas id="num_employees_per_nationality" height="100" width="100"></canvas>
	</div>
</div>

<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	attr = {
  	  		dataX: <%= @nationalities_names %>,
  	  		dataY: <%= @num_employees_per_nationality %>,
  	  		id: "num_employees_per_nationality",
  	  		type: "bar",
	  		xAxesTicksAutoSkip: true
  	  	}
  	  	chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_chart_num_employees_per_nationality_engineering.html.erb
<div class="chart-wrapper">
	<div class="title">
		Num. employees per nationality Engineering
	</div>
	<div class="canvas-wrapper-one-third">
		<canvas id="num_employees_per_nationality_engineering" height="100" width="100"></canvas>
	</div>
</div>


<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	attr = {
	  		dataX: <%= @nationalities_names_engineering %>,
	  		dataY: <%= @num_employees_per_nationality_engineering %>,
	  		id: "num_employees_per_nationality_engineering",
	  		type: "bar",
	  		xAxesTicksAutoSkip: true
	  	};
		chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_chart_num_employees_per_nationality_people.html.erb
<div class="chart-wrapper">
	<div class="title">
		Num. employees per nationality People
	</div>
	<div class="canvas-wrapper-one-third">
		<canvas id="num_employees_per_nationality_people" height="100" width="100"></canvas>
	</div>
</div>



<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	
  	  	attr = {
	  		dataX: <%= @nationalities_names_people %>,
	  		dataY: <%= @num_employees_per_nationality_people %>,
	  		id: "num_employees_per_nationality_people",
	  		type: "bar",
	  		xAxesTicksAutoSkip: true
	  	};
		chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_charts-num-employees.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<!-- CHART 1: Num. employees per nationality -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per nationality
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employees_per_nationality" height="100" width="120"></canvas>
			</div>
		</div>
	</div>

	<div class="col-xs-12 col-sm-6">
		<!-- CHART 2: Num -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per nationality Engineering
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employees_per_nationality_engineering" height="100" width="120"></canvas>
			</div>
		</div>
	</div>
</div>

<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	// Chart 1: num employees per nationality
	  	attr = {
	  		dataX: <%= @nationalities_names %>,
	  		dataY: <%= @num_employees_per_nationality %>,
	  		id: "num_employees_per_nationality",
	  		type: "bar",
	  		xAxesTicksAutoSkip: true
	  	}
		chartBarGenerator(attr);

		// Chart 2: num_employees_per_nationality_engineering
	  	attr = {
	  		dataX: <%= @nationalities_names_engineering %>,
	  		dataY: <%= @num_employees_per_nationality_engineering %>,
	  		id: "num_employees_per_nationality_engineering",
	  		type: "bar",
	  		xAxesTicksAutoSkip: true
	  	};
	  	chartBarGenerator(attr);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/analytics/_charts-wrapper-backup.html.erb
<div class="charts-wrapper">

	<div class="charts-row">
		<!-- CHART 1: Num. employees per nationality -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per nationality
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employees_per_nationality" height="100" width="100"></canvas>
			</div>
		</div>

		<!-- CHART 5: Num -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per nationality Engineering
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employees_per_nationality_engineering" height="100" width="100"></canvas>
			</div>
		</div>
		<!-- CHART 6: Num -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per nationality People
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employees_per_nationality_people" height="100" width="100"></canvas>
			</div>
		</div>

	</div>
	<div class="charts-row">
		<!-- CHART 4: Num -->
		<div class="chart-wrapper">
			<div class="title">
				Evolution average age
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="evolution_average_age" height="100" width="100"></canvas>
			</div>
		</div>

		<!-- CHART 1: Num. employees per division -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per division
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employees_per_division" height="100" width="100"></canvas>
			</div>
		</div>

		<!-- CHART 3: Num. employees per age group -->
		<div class="chart-wrapper">
			<div class="title">
				Num. employees per age group
			</div>
			<div class="canvas-wrapper-one-third">
				<canvas id="num_employee_per_age_group_array" height="100" width="100"></canvas>
			</div>
		</div>
	</div>

	<div class="charts-row">
		<!-- CHART 1: Num. employees per division -->
		<div class="chart-wrapper">
			<div class="title">
				New Employees per month
			</div>
			<div class="canvas-wrapper-three-thirds">
				<canvas id="new_employees_per_month" height="100" width="300"></canvas>
			</div>
		</div>
	</div>
</div>

app/views/pages/analytics/_left_menu.html.erb
<div class="left-menu">
	<div class="item">
		<div class="icon-wrapper">
			<i class="fa fa-users" aria-hidden="true"></i>
		</div>
		Num. employees
	</div>
	<div class="item">
		<div class="icon-wrapper">
			<i class="fa fa-flag" aria-hidden="true"></i>
		</div>
		Nationality
	</div>
	<div class="item">
		<div class="icon-wrapper">
			<i class="fa fa-child" aria-hidden="true"></i>
		</div>
		Age
	</div>
	<div class="item">
		<div class="icon-wrapper">
			<i class="fa fa-user-plus" aria-hidden="true"></i>
		</div>
		New Employees
	</div>
	<div class="item">
		<div class="icon-wrapper">
			<i class="fa fa-calendar-check-o" aria-hidden="true"></i>
		</div>
		Longevity
	</div>
	<div class="item">
		<div class="icon-wrapper">
			<i class="fa fa-wrench" aria-hidden="true"></i>s
		</div>
		Skills
	</div>
</div>

app/views/pages/analytics/_script_data.html.erb
<script type="application/javascript">
	<% content_for(:chart_js) do %>
	  <%= javascript_tag do %>
	  	// Chart 1: num employees per division
	  	let attr = {
	  		dataX: <%= @division_names %>,
	  		dataY: <%= @num_employees_per_division %>,
	  		id: "num_employees_per_division",
	  		type: "bar",
	  	}
		chartBarGenerator(attr.dataX, attr.dataY, attr.id, attr.type);

	  	// Chart 2: num employees per nationality
	  	attr = {
	  		dataX: <%= @nationalities_names %>,
	  		dataY: <%= @num_employees_per_nationality %>,
	  		id: "num_employees_per_nationality",
	  		type: "bar",
	  	}
		chartBarGenerator(attr.dataX, attr.dataY, attr.id, attr.type);

		// Chart 3: num employees per age group
	  	attr = {
	  		dataX: ["< 30", "31 - 40", "41 - 50", "51 - 65"],
	  		dataY: <%= @num_employee_per_age_group_array %>,
	  		id: "num_employee_per_age_group_array",
	  		type: "bar",
	  	}
		chartBarGenerator(attr.dataX, attr.dataY, attr.id, attr.type);

		// Chart 4: num employees per age group
		let firstYearsDays = <%= @first_years_days %>;
		let monthlyAgesAverages = <%= @monthly_ages_averages %>;
		linearChartGenerator(firstYearsDays, monthlyAgesAverages);

		// Chart 5: num_employees_per_nationality_engineering
	  	attr = {
	  		dataX: <%= @nationalities_names_engineering %>,
	  		dataY: <%= @num_employees_per_nationality_engineering %>,
	  		id: "num_employees_per_nationality_engineering",
	  		type: "bar",
	  	};
		chartBarGenerator(attr.dataX, attr.dataY, attr.id, attr.type);

		// Chart 6: num_employees_per_nationality_people
	  	attr = {
	  		dataX: <%= @nationalities_names_people %>,
	  		dataY: <%= @num_employees_per_nationality_people %>,
	  		id: "num_employees_per_nationality_people",
	  		type: "bar",
	  	};
		chartBarGenerator(attr.dataX, attr.dataY, attr.id, attr.type);

		// Chart 7: num_employees_per_nationality_people
	  	attr = {
	  		dataX: <%= @inc_months %>,
	  		dataY: <%= @incorporations %>,
	  		id: "new_employees_per_month",
	  		type: "bar",
	  	};
		chartBarGenerator(attr.dataX, attr.dataY, attr.id, attr.type);
		
	  <% end %>
	<% end %>
</script>

app/views/pages/home.html.erb
<div class="home-page">
	<div class="banner">
		<div class="title">
			WAY Book Analytics
		</div>
		<div class="cover-pic-wrapper">
			<%= link_to analytics_path do  %>
				<%= image_tag("analytics-charts", size: "630x389") %>
			<% end %>
		</div>
		<div class="sentence">
			Decision-making with live company dataaaa
		</div>
	</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <div class="left-navbar">
    <%= link_to root_path do  %>
      <div class="logo">
        <%= image_tag("way-analytics", size: "125x25") %>
      </div>
    <% end %>
  </div>

  <div class="right-navbar">
    
    <div class="other-apps">
        <div class="dropdown">
      <i class="fa fa-th icon" aria-hidden="true" class="dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"></i>

      <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <div class="other-apps-content">
          <div class="roww">
            <%= link_to root_path, class: "link colo1" do  %>
              <i class="fa fa-pie-chart icon" aria-hidden="true"></i>
              <div class="text">
                WAY Data
              </div>
            <% end %>
            <a target="_blank" href="http://www.zep.de/" class="link colo2">
              <i class="fa fa-clock-o icon" aria-hidden="true"></i>
              <div class="text">
                WAY ZEP
              </div>
            </a>
          </div>
          <div class="roww">
            <a target="_blank" href="https://schulungssystem.waygroup.de/" class="link colo3">
              <i class="fa fa-file-text-o icon" aria-hidden="true"></i>
              <div class="text">
                W.H.A.T.
              </div>
            </a>
            <a target="_blank" href="http://www.waygroup.de/" class="link colo4">
              <i class="fa fa-home icon" aria-hidden="true"></i>
              <div class="text">
                Way Group
              </div>
            </a>
          </div>
        </div>
      </div>
        </div>
      </div>

      <!-- Profile picture with dropdown list -->
      <% if user_signed_in? %>
        <div class="dropdown">
            <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar avatar-cursor dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">

            <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <div class="avatar-navbar-content-wrapper">
                <div class="user-name">
                  <%= current_user.email %>
                </div>
                <%= link_to destroy_user_session_path, method: :delete, class: "link" do %>
                  <i class="fa fa-sign-out icon"></i>
                  Log out
                <% end %>
            </div>
          </div>
            
        </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
          
  </div>
    
</div>